contact_links:
  - name: Question
    url: https://github.com/sof202/EpigenomicsLabWeb/discussions/categories/q-a
    about: If you have any questions, head over to the discussions page to ask members of the community
