name: Publication request
description: Make a request to add a new publication to the research section of the website
title: "[New Publication]: "
labels: ["Publication"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request!
  - type: textarea
    id: name
    attributes:
      label: "What is the title of the publication?" 
    validations:
      required: true
  - type: textarea
    id: Who
    attributes:
      label: "Which members of the Lab worked on this paper?"
      validations:
        required: true
  - type: textarea
    id: Where
    attributes:
      label: "Where can the publication be found?"
      validations:
        required: true
  - type: textarea
    id: What
    attributes:
      label: "Give a short summary of the publication"
      description: This is to ensure that we add the correct tags to the publication
      validations:
        required: true
