name: Publication request
description: Make a request to add a new publication to the research section of the website
title: "[New Publication]: "
labels: ["Publication"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request!
  - type: dropdown
    id: found
    attributes:
      label: "Can the publication be found on Dimensions?"
      description: "Go to app.dimensions.ai and try to find your publication using the filters."
      multiple: false
      options:
        - Yes
        - No
    validations:
      required: true
  - type: textarea
    id: How
    attributes:
      label: "How can the publication be found on Dimensions?"
      description: "Ideally it can be found by filtering to a PI in our team. If so, please just enter the PI's name here."
    validations:
      required: true
